### ISSUE TITLE
imap.gmail.com - possible SNI issue?

### ISSUE THREAD

**Issue by sudofox** [joeyates/imap-backup#57]
I decided to try imap-backup, but when I went to perform a backup on a G Suite account (via imap.gmail.com):

    Unexpected error: SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate)

This may be related to the following: https://bugzilla.redhat.com/show_bug.cgi?id=1611815

Can you confirm/reproduce? I'm on Arch Linux (4.18.7-arch1-1-ARCH).

**Comment by sudofox** [comment]
Sorry for the delayed response.

There's no private information other than my email address in the output, so here:

```
D, [2018-10-10T09:43:42.282265 #32452] DEBUG -- : Running backup of account: <email address of mine that uses G Suite>
D, [2018-10-10T09:43:42.282392 #32452] DEBUG -- : Creating IMAP instance: imap.gmail.com, options: {:port=>993, :ssl=>true}
Traceback (most recent call last):
	13: from /home/aburk/.gem/ruby/2.5.0/bin/imap-backup:23:in `<main>'
	12: from /home/aburk/.gem/ruby/2.5.0/bin/imap-backup:23:in `load'
	11: from /home/aburk/.gem/ruby/2.5.0/gems/imap-backup-1.3.0/bin/imap-backup:69:in `<top (required)>'
	10: from /home/aburk/.gem/ruby/2.5.0/gems/imap-backup-1.3.0/lib/imap/backup/configuration/list.rb:17:in `each_connection'
	 9: from /home/aburk/.gem/ruby/2.5.0/gems/imap-backup-1.3.0/lib/imap/backup/configuration/list.rb:17:in `each'
	 8: from /home/aburk/.gem/ruby/2.5.0/gems/imap-backup-1.3.0/lib/imap/backup/configuration/list.rb:19:in `block in each_connection'
	 7: from /home/aburk/.gem/ruby/2.5.0/gems/imap-backup-1.3.0/bin/imap-backup:70:in `block in <top (required)>'
	 6: from /home/aburk/.gem/ruby/2.5.0/gems/imap-backup-1.3.0/lib/imap/backup/account/connection.rb:41:in `run_backup'
	 5: from /home/aburk/.gem/ruby/2.5.0/gems/imap-backup-1.3.0/lib/imap/backup/account/connection.rb:56:in `imap'
	 4: from /home/aburk/.gem/ruby/2.5.0/gems/imap-backup-1.3.0/lib/imap/backup/account/connection.rb:56:in `new'
	 3: from /usr/lib/ruby/2.5.0/net/imap.rb:1092:in `initialize'
	 2: from /usr/lib/ruby/2.5.0/net/imap.rb:1531:in `start_tls_session'
	 1: from /usr/lib/ruby/2.5.0/net/protocol.rb:44:in `ssl_socket_connect'
/usr/lib/ruby/2.5.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate) (OpenSSL::SSL::SSLError)
```

**Comment by msbit** [comment]
Out of curiosity, does the output of:

    openssl s_client -connect imap.gmail.com:993 -CAfile /etc/ssl/cert.pem < /dev/null > /dev/null

and:

    openssl s_client -connect imap.gmail.com:993 -servername imap.gmail.com -CAfile /etc/ssl/cert.pem < /dev/null > /dev/null

differ? The first is without SNI and the second with. Your `-CAfile` argument might differ, this is mine under macOS. Under Ubuntu it's `/etc/ssl/certs/ca-certificates.crt`.

For me, the output of both is:

```
depth=2 OU = GlobalSign Root CA - R2, O = GlobalSign, CN = GlobalSign
verify return:1
depth=1 C = US, O = Google Trust Services, CN = Google Internet Authority G3
verify return:1
depth=0 C = US, ST = California, L = Mountain View, O = Google LLC, CN = imap.gmail.com
verify return:1
```

`verify return:1` indicates that the certificate is trusted.

**Comment by sudofox** [comment]
I get the same result for both.

```
aburk@aburk:~$ openssl s_client -connect imap.gmail.com:993 -CAfile /etc/ssl/cert.pem < /dev/null > /dev/null
depth=2 OU = GlobalSign Root CA - R2, O = GlobalSign, CN = GlobalSign
verify return:1
depth=1 C = US, O = Google Trust Services, CN = Google Internet Authority G3
verify return:1
depth=0 C = US, ST = California, L = Mountain View, O = Google LLC, CN = imap.gmail.com
verify return:1
DONE
aburk@aburk:~$ openssl s_client -connect imap.gmail.com:993 -servername imap.gmail.com -CAfile /etc/ssl/cert.pem < /dev/null > /dev/null
depth=2 OU = GlobalSign Root CA - R2, O = GlobalSign, CN = GlobalSign
verify return:1
depth=1 C = US, O = Google Trust Services, CN = Google Internet Authority G3
verify return:1
depth=0 C = US, ST = California, L = Mountain View, O = Google LLC, CN = imap.gmail.com
verify return:1
DONE
```

I tested with a straight gmail address as well, and got the same result as with the G Suite email: self-signed certificate.

```
D, [2018-10-23T15:53:00.013554 #1066] DEBUG -- : Creating IMAP instance: imap.gmail.com, options: {:port=>993, :ssl=>true}
Unexpected error: SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate)
```

**Comment by msbit** [comment]
Yep, I took a look at the Fedora issue, but I don't think it applies in this case, for a few reasons:

* it applies to the `fetchmail` program, and `imap-backup` is Ruby all the way down,
* the patch simply adds the SNI extension to the request, and
* `imap.gmail.com` returns the same set of certificates when requested with SNI and without, as shown by the output of OpenSSL on both our machines

I'm going to take a look at whether this is a Linux specific kind of thing - my hunch is that the certificate store that Ruby looks at isn't the same as the one the system looks at.

**Comment by getconor** [comment]
Been using imap-backup for over a year, recently it started failing with the same error as detailed by OP.

I can confirm that the first method still fails while the second method succeeds.

**Comment by joeyates** [comment]
On a live distro of Arch Linux 4.20, the first script fails. I'll use that to sort out a fix.

**Comment by joeyates** [comment]
In order to track down what is causing this, whoever is seeing the issue, please submit the following info:

* operating system + version
* openssl version
* Ruby version
* imap-backup version

**Comment by joeyates** [comment]
Fails with:

Operating system: Arch Linux 4.20.0-arch1-1-ARCH

openssl:
```
$ openssl version
OpenSSL 1.1.1a 20 Nov 2018
```

Ruby:
```
$ ruby -v
ruby 2.5.3p105 ...
```

imap-backup:
```
$ imap-backup -v
2.0.0.rc2
```

**Comment by joeyates** [comment]
I've released v2.0.0.rc3 with a fix. I'm also creating a maintenance branch for 1.x with a backport.

**Comment by joeyates** [comment]
I've released v1.4.0 as a maintenance release of the 1.x code including this fix.

**Comment by joeyates** [comment]
@sudofox Could you check if this solves the original problem?

**Comment by nosilver4u** [comment]
Fails with:

Operating system: Debian 9

openssl:
```
$ openssl version
OpenSSL 1.1.0j 20 Nov 2018
```

Ruby:
```
$ ruby -v
ruby 2.3.3p222 ...
```

imap-backup:
```
$ imap-backup -v
1.3.0
```

Ruby openssl version:
```
$ ruby -ropenssl -e "puts OpenSSL::VERSION"
1.1.0
```

I'll also see if I can update to 1.4.0 and test it out.

**Comment by nosilver4u** [comment]
Is there any additional configuration I need with 1.4.0? I'm still getting what appears to be the same exact output:
```
D, [2019-01-08T17:04:08.378999 #21082] DEBUG -- : Running backup of account: my-email@ewww.io
D, [2019-01-08T17:04:08.379247 #21082] DEBUG -- : Creating IMAP instance: imap.gmail.com, options: {:port=>993, :ssl=>true}
D, [2019-01-08T17:04:08.485806 #21082] DEBUG -- : Logging in: my-email@ewww.io/xxxxxxxxxxxxxxxx
/usr/lib/ruby/2.3.0/net/imap.rb:1196:in `get_tagged_response':  Invalid credentials (Failure) (Net::IMAP::NoResponseError)
	from /usr/lib/ruby/2.3.0/net/imap.rb:1250:in `block in send_command'
	from /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /usr/lib/ruby/2.3.0/net/imap.rb:1232:in `send_command'
	from /usr/lib/ruby/2.3.0/net/imap.rb:436:in `login'
	from /var/lib/gems/2.3.0/gems/imap-backup-1.4.0/lib/imap/backup/account/connection.rb:66:in `imap'
	from /var/lib/gems/2.3.0/gems/imap-backup-1.4.0/lib/imap/backup/account/connection.rb:47:in `run_backup'
	from /var/lib/gems/2.3.0/gems/imap-backup-1.4.0/bin/imap-backup:75:in `block in <top (required)>'
	from /var/lib/gems/2.3.0/gems/imap-backup-1.4.0/lib/imap/backup/configuration/list.rb:19:in `block in each_connection'
	from /var/lib/gems/2.3.0/gems/imap-backup-1.4.0/lib/imap/backup/configuration/list.rb:17:in `each'
	from /var/lib/gems/2.3.0/gems/imap-backup-1.4.0/lib/imap/backup/configuration/list.rb:17:in `each_connection'
	from /var/lib/gems/2.3.0/gems/imap-backup-1.4.0/bin/imap-backup:74:in `<top (required)>'
	from /usr/local/bin/imap-backup:22:in `load'
	from /usr/local/bin/imap-backup:22:in `<main>'
```

Also, same output as earlier users when running the openssl commands "verify return:1"

**Comment by joeyates** [comment]
@nosilver4u have you got a `"connection_options"` entry in your `~/.imap_backup/config`?

If so, please remove that key.

With 1.4.0, this line in your output:

```
D, [2019-01-08T17:04:08.379247 #21082] DEBUG -- : Creating IMAP instance: imap.gmail.com, options: {:port=>993, :ssl=>true}
```

should have shown this:

```
D, [2019-01-08T17:04:08.379247 #21082] DEBUG -- : Creating IMAP instance: imap.gmail.com, options: {:port=>993, :ssl=>{:ssl_version=>:TLSv1_2}}
```

**Comment by nosilver4u** [comment]
Yeah I am, but I'm going to generate a new one, maybe I messed up the password somehow...
And no I don't have connection_options in my  config. I did once to see if that helped, but it's no longer there.

**Comment by nosilver4u** [comment]
New password doesn't seem to have changed anything, it's still saying Invalid credentials. I'll reach out to Google and see if they can shed any light on it.

**Comment by joeyates** [comment]
@nosilver4u According to this article https://support.google.com/mail/answer/7126229?hl=en&visit_id=636825719338260815-2122557143&rd=2#cantsignin you may need to go to the DispayUnlockCapthcha page

**Comment by nosilver4u** [comment]
Just tried that and it didn't work either, guess I'll just wait to see if their support can provide any insight.

**Comment by nosilver4u** [comment]
@joeyates I just got this again, so perhaps it is still an SSL vs. TLS issue with my install?
"Google prevented someone from signing in to your account using a non-Google app."
I have it running via cron, obviously it's been failing every day, but today it finally threw this error again, and the IP address it lists is from the server where the cronjob runs.

**Comment by Keruspe** [comment]
This issue probably fixes this issue without your workaround: https://github.com/ruby/ruby/pull/2077

**Comment by nosilver4u** [comment]
That's a very good possibility, thanks for mentioning that!

**Comment by sebastianst** [comment]
Same error on Arch Linux with `imap-backup 1.4.1`, `ruby 2.6.1p33 (2019-01-30 revision 66950)`, `OpenSSL 1.1.1a` and `ruby -ropenssl -e "puts OpenSSL::VERSION"` is `2.1.2`.
```
Unexpected error: SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate)
```

**Comment by joeyates** [comment]
Reopening

**Comment by Keruspe** [comment]
Fwiw, I also posted the patch here: https://bugs.ruby-lang.org/issues/15594

Not sure what else to do to get some progress on this

**Comment by nibra** [comment]
Fails with

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic

$ uname -orm
4.18.0-14-generic x86_64 GNU/Linux

$ openssl version
OpenSSL 1.1.1  11 Sep 2018

$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

$ imap-backup -v
1.4.1

$ ruby -ropenssl -e "puts OpenSSL::VERSION"
2.1.1

I'm using imap-backup in a cronjob that stopped working after January, 31st (timestamp of the last backup).

**Comment by joeyates** [comment]
@sebastianst and @nibra could you post the following?

1. the `Creating IMAP` line from your debug output,
2. an **anonymized** version of your `~/.imap-backup/config.json`

Thanks.

**Comment by nibra** [comment]
D, [2019-02-18T10:04:00.429220 #4556] DEBUG -- : Creating IMAP instance: imap.gmail.com, options: {:port=>993, :ssl=>true}

{
  "accounts": [
    {
      "username": "info@bgw-breklum.net",
      "password": "********",
      "local_path": "/home/****/Mails/Backup",
      "folders": [

      ],
      "server": "imap.gmail.com"
    }
  ],
  "debug": true
}

**Comment by joeyates** [comment]
The previous fix was only being applied to @gmail accounts.

This should now be fixed for custom domains in 2.0.0.rc4 (and 1.4.2).

You should get `{:ssl_version=>:TLSv1_2}`, like this:

```
D, [2019-01-08T17:04:08.379247 #21082] DEBUG -- : Creating IMAP instance: imap.gmail.com, options: {:port=>993, :ssl=>{:ssl_version=>:TLSv1_2}}
```

@nibra @sebastianst Please check.

**Comment by nibra** [comment]
Updating to 1.4.2 solved the issue for me. Thank you!

**Comment by joeyates** [comment]
@nosilver4u Does the new release solve the problem for you too?

**Comment by nosilver4u** [comment]
Updated to 1.4.2, but still getting the same error.
```D, [2019-02-26T15:37:34.433567 #5023] DEBUG -- : Running backup of account: xxxxxx@xxxxxx
D, [2019-02-26T15:37:34.434147 #5023] DEBUG -- : Creating IMAP instance: imap.gmail.com, options: {:port=>993, :ssl=>{:ssl_version=>:TLSv1_2}}
D, [2019-02-26T15:37:34.498513 #5023] DEBUG -- : Logging in: xxxxxx@xxxxxx/xxxxxxxxxxxxxxxx
/usr/lib/ruby/2.3.0/net/imap.rb:1196:in `get_tagged_response':  Invalid credentials (Failure) (Net::IMAP::NoResponseError)
        from /usr/lib/ruby/2.3.0/net/imap.rb:1250:in `block in send_command'
        from /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
        from /usr/lib/ruby/2.3.0/net/imap.rb:1232:in `send_command'
        from /usr/lib/ruby/2.3.0/net/imap.rb:436:in `login'
        from /var/lib/gems/2.3.0/gems/imap-backup-1.4.2/lib/imap/backup/account/connection.rb:66:in `imap'
        from /var/lib/gems/2.3.0/gems/imap-backup-1.4.2/lib/imap/backup/account/connection.rb:47:in `run_backup'
        from /var/lib/gems/2.3.0/gems/imap-backup-1.4.2/bin/imap-backup:75:in `block in <top (required)>'
        from /var/lib/gems/2.3.0/gems/imap-backup-1.4.2/lib/imap/backup/configuration/list.rb:19:in `block in each_connection'
        from /var/lib/gems/2.3.0/gems/imap-backup-1.4.2/lib/imap/backup/configuration/list.rb:17:in `each'
        from /var/lib/gems/2.3.0/gems/imap-backup-1.4.2/lib/imap/backup/configuration/list.rb:17:in `each_connection'
        from /var/lib/gems/2.3.0/gems/imap-backup-1.4.2/bin/imap-backup:74:in `<top (required)>'
        from /usr/local/bin/imap-backup:22:in `load'
        from /usr/local/bin/imap-backup:22:in `<main>'```

**Comment by joeyates** [comment]
@nosilver4u The issue you're having seems to be related to some problem with authentication with GMail. I've opened #64 to track this problem. The fact that you're having that problem means that TLS negotiation is succeeding, so I think you problem is unrelated to this issue.

Please feel free to reopen if you feel that this is not the case.
